name: release
on:
  repository_dispatch:
    types: [release]
  schedule:
    # We want the release to be at 10 or 11am Pacific Time
    # We also make this an hour after all others such as Sentry,
    # Snuba, and Relay to make sure their releases finish.
    - cron:  '0 18 15 * *'
jobs:
  release:
    runs-on: ubuntu-latest
    name: "Release a new version"
    steps:
        - id: calver
          if: ${{ !github.event.client_payload.version }}
          run: echo "::set-output name=version::$(date +'%y.%-m.0')"
        - uses: actions/checkout@v2
        - uses: getsentry/craft@master
          if: ${{ !github.event.client_payload.skip_prepare }}
          with:
            action: prepare
            version: ${{ github.event.client_payload.version || steps.calver.outputs.version }}
          env:
            DRY_RUN: ${{ github.event.client_payload.dry_run }}
            GIT_COMMITTER_NAME: getsentry-bot
            GIT_AUTHOR_NAME: getsentry-bot
            EMAIL: bot@getsentry.com
        - uses: getsentry/craft@master
          with:
            action: publish
            version: ${{ github.event.client_payload.version || steps.calver.outputs.version }}
            keep_branch: '--keep-branch'
            no_merge: '--no-merge'
          env:
            DRY_RUN: ${{ github.event.client_payload.dry_run }}
            GIT_COMMITTER_NAME: getsentry-bot
            GIT_AUTHOR_NAME: getsentry-bot
            EMAIL: bot@getsentry.com
